### PR TITLE
Remove breaking change by automatically migrating the vacuum's topic to an entity_id

### PR DESCRIPTION
**Pull request by rohankapoorcom**
This should be working (except for the part where it automatically reloads the config entry when the race condition occurs).

I'm still working on fixing that error situation. I know the issue (it's a race condition - MQTT is loaded but the devices aren't processed at the time this component is loaded), but I'm trying to figure out how to tell Home Assistant that it needs to retry the integration.

Please hold off on merging until I find a fix for that.

### CODE REVIEW

**Review by sca075 — APPROVED** [review]

**Comment by sca075** [comment]
I did work on it too and I'm going to upload the changes I made, please hold on a sec.

**Comment by sca075** [comment]
@rohankapoorcom  the solution I send it by email. There is just to correct one error because of the changes: Ignoring invalid device info: Invalid device info {'identifiers': None} for 'valetudo_vacuum_camera' config entry: device info must include at least one of identifiers or connections      This should be in the config_flow as you will see

**Comment by sca075** [comment]
if you have a discord I will send you my ID and we can communicate more easier ;)

**Comment by rohankapoorcom** [comment]
I pushed my change as well https://github.com/sca075/valetudo_vacuum_camera/pull/26

I'm on discord as the same name as I am on github.

**Comment by sca075** [comment]
discord sandro0538

**Pull request merged**
