### PR TITLE
2024.05

### PR DESCRIPTION
**Pull request by sca075**
Cleaning and refactoring process.
* [x] Replace gzip and zlib with isal as per discussed in #126  
* [x] Refactor the img_data.py
* [x] Refactoring of camera.py.
* [x]  Refactoring camera_processing.py
* [x] Threading snapshots.
* [x] Refine rand256 images.
* [x] Verify Hypfer firmware after changes on img_data.py are completed.
* [x] Isort and Blacking the files.

### CODE REVIEW

**Comment by sca075** [comment]
The development on rand256 will be skip, some minor adjustment only will be release. The firmware currently isn't supporting most of the capability available on Hypfer. The camera primary goal is to render the available functions offered from the firmwares.

**Comment by sca075** [comment]
Could do some adjustments on f6abca1cc6f9cba7e46f5f5a31bf87fb807e0e23 to get right the rotation of the rand256 robots. Therefore we removed the todo from the list. Also, since rand256 do not update the status, we do render directly the vacuum state when it is connected.

**Comment by tjorim** [comment]
I just tried out the 2024.05 branch and it worked fine for me.

**Comment by sca075** [comment]
> I just tried out the 2024.05 branch and it worked fine for me.

I'm rebooting HA several times (now installing the b2) and I found out something is wrong with the data from MQTT, sometimes payload.decode() do not work, some other yes.. mmmm driving me crazy.. probably it is because of python 312 but I'm working to found a solution for it.

**Comment by sca075** [comment]
> > I just tried out the 2024.05 branch and it worked fine for me.
> 
> I'm rebooting HA several times (now installing the b2) and I found out something is wrong with the data from MQTT, sometimes payload.decode() do not work, some other yes.. mmmm driving me crazy.. probably it is because of python 312 but I'm working to found a solution for it.

Found the rout cause (sometimes binary data some other time strings) I did add a function to check the type of data in the payload (great that they raised the quality scale to platinum for MQTT)... okay anyway thanks for the feedback @tjorim you are a great contributor here and I really appreciate the cooperation :)

**Comment by sca075** [comment]
> Does the data not come from the vacuum directly over MQTT instead of through HA?

As nothing changed on the firmware of the Vacuums, I suspect something is changing on MQTT (it was mainly in the payload for the $state, that the value was binary and sometime string). I don't know honestly from were it comes.. anyhow it good to detect it during the tests ;)

**Pull request merged**
